### ISSUE TITLE
mdict词典查询成功后，各field的窗口不能编辑

### ISSUE THREAD

**Issue by TheKiteRunning** [finalion/WordQuery#10]
你好，如题，详情：

「编辑」窗口是指：

![image](https://cloud.githubusercontent.com/assets/24802332/23505297/fa39d176-ff7d-11e6-9f37-67ad77366804.png)

所采用的词典为：

- 牛津英语搭配词典.mdx
- Chamber’s Dictionary 11th.mdx
- Dictionary_com_Unabridged_2015.mdx

![image](https://cloud.githubusercontent.com/assets/24802332/23505273/d1b5ac48-ff7d-11e6-9677-ff702d309ec3.png)

非常感谢!

**Comment by TheKiteRunning** [comment]
更有趣了，电脑上虽然可以preview，但是复习的时候反面不显示（mdict的释义字段在反面）。手机上可以显示出来，但有很短暂的缓冲过程。见下图中的蓝色矩形上面的省略号，请问大致是什么问题造成的呢，感谢！

![screenshot_2017-03-03-09-15-26-538_com ichi2 anki](https://cloud.githubusercontent.com/assets/24802332/23534345/5300b30a-fff2-11e6-9097-f449dc96bb59.png)

**Comment by finalion** [comment]
这个应该是字典的问题。Merriam Webster's Collegiate Dictionary and Thesaurus 2015 这个字典，添加释义后，不能显示，但是可以review。后来检查应该是它的html有问题

**Comment by TheKiteRunning** [comment]
感谢回复，的确应该一个一个地检查，之前担心更改option出新的bug，一直不敢动。试了一下手头的词典，windows上不能正常显示的有：

- Merriam Webster's Collegiate Dictionary and Thesaurus 2015 
- Dictionary_com_Unabridged_2015
- Oxford_English_Dictionary_2nd_v4

效果比较好的有：
- Vocabulary.com Dictionary
- Chamber’s Dictionary 11th
- 牛津搭配词典

**Comment by finalion** [comment]
是的，字典太多了，想统一太难。所以你可以按预留的几个接口扩展字典。

不要怕嘛，有问题才好解决：）

**Comment by WeiChienHsing** [comment]
想问那个@@@link=.这个要怎么解决啊.我用的一个日文字典查询出来都是这个.

**Comment by finalion** [comment]
@WeiChienHsing 没注意这个。是不是字典的问题，能把你的字典发出来看下？

**Comment by WeiChienHsing** [comment]
@finalion  好像是字典redirect的问题.@@@LINK那个第一张图Dictionary字段也出现了.

**Comment by finalion** [comment]
@WeiChienHsing 我手头没有这种字典，我按你说的改一下，你帮忙测试看看

**Comment by finalion** [comment]
@WeiChienHsing  改好了，dev分支。 https://github.com/finalion/WordQuery/archive/dev.zip

**Comment by WeiChienHsing** [comment]
@finalion 感谢.在你分支上稍微改了改.我的问题解决了.

**Comment by finalion** [comment]
@WeiChienHsing 怎么改的发上来啊，我这也更新一下

**Comment by WeiChienHsing** [comment]
··    @export(u"完整解释", 0)
    def fld_whole(self):
        if not self.builder:
            self.index()
        result = self.builder.mdx_lookup(self.word)
        if result:
            if result[0].find("@@@LINK") > -1 :
                self.word = result[0][8:-2]
                return self.fld_whole()
            else :
                ss = self.adapt_to_anki(result[0])
                # open('d:\\wmu.html', 'wb').write(ss)
                return QueryResult(result=ss[0], js=ss[1])
        return self.default_result··

**Comment by finalion** [comment]
@WeiChienHsing 递归前那里为什么取-2索引？如果这里没什么问题的话，我就合并了

**Comment by WeiChienHsing** [comment]
@finalion 这个问题有点吊诡。我也不大清楚,我刚开始是把＠＠＠LINK=XX中的＠＠＠LINK=给替换掉了。用showInfo来看确实是只剩下XX这两个字符。但是查询不到结果。后来用了一下len函数。发现结果是5个字符，所以就从后面往前两个试了一下。就可以正常查询到了，我猜是换行符/r/n之类的。

**Comment by finalion** [comment]
@WeiChienHsing 没有其他有意义字符就行了，换行符空格啥的strip一下就行了。result[0][8:].strip()

**Comment by GarrisonBaird** [comment]
**Stop using magic numbers!!! Please!!!**
result[0][len("＠＠＠LINK="):].strip()

**Comment by TheKiteRunning** [comment]
百词斩取音频还挺好用的，只是不知道为甚么，出现几个bug：

- 音频下载成功，窗口中也有文件的链接，但播放失败。其它由tts产生的音频均可以正常播放。

- 查询时不时会弹出错误

![image](https://cloud.githubusercontent.com/assets/24802332/24453964/783c053c-14bc-11e7-8e56-41f0c872d5de.png)

- 错误的同时，会在上述报错信息之外，出现查询错误的情况，，如：

![image](https://cloud.githubusercontent.com/assets/24802332/24454278/dc050eaa-14bd-11e7-995d-92df3323d586.png)

![image](https://cloud.githubusercontent.com/assets/24802332/24454036/beaed922-14bc-11e7-8604-2c421a46a83a.png)

感谢！

**Comment by finalion** [comment]
@TheKiteRunning 已更新。
