### ISSUE TITLE
Add stardict support

### ISSUE THREAD

**Issue by GarrisonBaird** [finalion/WordQuery#11]
There are bunches of dictionaries in stardict (.ifo) format, it will be awesome if this addon supports stardict. 
This won't be difficult as there are some libraries/tools already exsit and we can make use of them.
 
_https://github.com/lig/pystardict ([example](https://github.com/shramana8310/Flashcards-Manager))
https://github.com/pysuxing/python-stardict
https://dushistov.github.io/sdcv/ (non-python)
https://github.com/cz7asm/pyStarDictViewer_

**Comment by finalion** [comment]
ok, I will take it into account. But If you are interested, you can fork and pull requests. Kiitos.

**Comment by GarrisonBaird** [comment]
i'm working on it, using [pystardict](https://github.com/lig/pystardict)

**Comment by GarrisonBaird** [comment]
Here is a working version, extended WebService
[stardict.py](https://gist.github.com/GarrisonBaird/e98a34bd06c8b768f581aebafea97db7)

**Comment by GarrisonBaird** [comment]
It's very difficult to implement another MdxService, I tried in 3 hours but still can't make it work, but easily made it with WebService in 30 minutes. 
Please consider redesining the code architecture, make WebService as a general interface for all dictionaries including MdxService, WebService can do everything like MdxService does, except configuration related stuff like choosing different dictionary for each field.

**Comment by finalion** [comment]
@GarrisonBaird Great work! I tried it and it works!

**Comment by finalion** [comment]
@GarrisonBaird Thanks your advice. I will make some improvements.

**Comment by finalion** [comment]
@GarrisonBaird I have mixed your code to the newest commit and now it support stardict format. You can add stardict folders as before, then it could recognize all the dictionaries automatically.
