### ISSUE TITLE
Fields in Options dialog will be overlapped after adding a new field

### ISSUE THREAD

**Issue by GarrisonBaird** [finalion/WordQuery#14]
1. Open Options dialog, choose a note type, click ok to save the configuration
2. Add a new field to that not type
3. Open Options dialog again, you should see last two fields are overlapped
4. Restart Anki, open Options dialog again, they are still overlapped
5. Delete `addons/wquery/.wqcfg`, they are displayed correctly

**Comment by finalion** [comment]
fixed, thanks.
