### ISSUE TITLE
百词斩wordquery时的小问题

### ISSUE THREAD

**Issue by TheKiteRunning** [finalion/WordQuery#19]
你好，手机上不知道怎么样传图～问题大致如下:

- 图片抓下来的都是网址链接，请问有没有办法直接显示为图片呢，是不是对模板有一定要求
- TV那一个直接报错

感谢感谢～

**Comment by finalion** [comment]
不用修改模板，加了个html标签，图片显示没问题了。TV那个报错可能是因为单词没有视频，插件没有处理导致的。已更新试一下，只把baicizhan.py替换下就可以
[baicizhan.zip](https://github.com/finalion/WordQuery/files/862048/baicizhan.zip)

**Comment by TheKiteRunning** [comment]
我也觉得是没有加标签，就是不会改，太感谢啦！

**Comment by TheKiteRunning** [comment]
没有头痛医脚哈哈哈，象形也是图片～照着您图片那个改了一下可以了～

```python
    @export(u'象形', 3)
    def fld_df(self):
    	url = self.cache_result('df') if self.cached('df') else self._get_from_api().get('df', '')
        return '<img src="{}">'.format(url)
```

**Comment by finalion** [comment]
嗯，其实这个在模板中适配可能会比较好。插件只是把有效信息提取出来
