### ISSUE TITLE
最新版WQ有道音标无法同时查询US与UK，还会出现无音标的情况。

### ISSUE THREAD

**Issue by Daniel-313** [finalion/WordQuery#24]
最新版查询有道英文时，会出现无音标的情况，或者大部分只有一个音标，不像以前两个音标都能查询到了。大佬能否改回来呀？

貌似批量查询有会出现重复获取的情况，上一个单词的内容全部复制到下一个单词去了。五百个单词以内貌似没遇到，但是一次性查6000个曾经每隔几十个就出现几个。。。

感谢大佬分享，一点小问题和大佬反馈一下，大佬有时间可以看看。

**Comment by GarrisonBaird** [comment]
for any privious version, click `<> Code` on the top left of the page, `xxx commits` below, 
find the version you need, `<>` button on the right, green `clone or download` button on the right, `Donload ZIP`
extract the zip file and copy to `C:\Users\xxx\Documents\Anki\addons` or `C:\用户\xxx\文档\Anki\addons` if your system is Chinese (I remember so, not very sure), restart Anki

**Comment by GarrisonBaird** [comment]
I get the second issue too, it happends when quering a word not exists in the dictionary
I'll check this issue after @finalion cleans his code...

**Comment by finalion** [comment]
@Daniel-313 音标问题是因为了用了一个新的更简单的api地址，发现和原来的api返回数据不一样，现在改回来了。
第二个问题我这没复现，但是出现有些单词查询不到的情况，但是单词查没问题。我再查一下

**Comment by Daniel-313** [comment]
@finalion 网络的有道汉英查询会出现这样的情况，也会有偶尔查不到，单个就能查询，或者有音标没释义的情况也有，然后这个释义重复多次查询也查不到。查不到倒是没啥关系，手动复制能替代，那是少数。主要是会出现串词的情况，不同单词相同释义和音标，这个比较苦恼。小批量好像就不存在这个问题，不知道是不是我网络的原因影响到了

**Comment by finalion** [comment]
网络词典的话，可能会出现这种问题，#23。 我看一下

**Comment by GarrisonBaird** [comment]
This issue affect not only netdict, but also localdict, I heavily use stardict and get the same issue very offen
I guess the some variables aren't gotten reset when getting some error (e.g. empty word field, empty dictionary response), the previous result is returned to next few queries

**Comment by finalion** [comment]
I have added delay for different services to ensure robust querying and inserting every time.
It didn't get errors in my tests. Try to update.
