### ISSUE TITLE
The nice Add-on cannot be run properly, both in MAC and Windows 10, Plz help.

### ISSUE THREAD

**Issue by lobstergy** [finalion/WordQuery#26]
First, I think it's great and huge when I heard of that there is an Anki add-on "WordQuery" can batch query words' definition from any MDX files,(like oxford and Merriam-Webster's) because most of the time the word-list collected from kindle mate when you finished a big novel can be very large, sometimes the words collection reach at hundreds even thousands, though "kindle mate" truly have dictionaries built in it, but none of them can be trust. So big thank you, Mr. Finalion for your great idea and efforts for that.
My question is, unfortunately, both on my MacBook pro and windows 10 (VMware fusion, virtual machine) the "wordquery" cannot be run properly. I'd followed the instruction, install the add-on, setting the MDX file folder, and then, stuck at the "choose note types". On windows 10, there are some errors when first try to launch the "wordquery". 
Plz, help me out. Thanks again!

some pics from my mac
<img width="710" alt="screenshot 2017-04-15 13 03 48" src="https://cloud.githubusercontent.com/assets/15153547/25060932/41eef7e6-21dc-11e7-9cfa-cd6663327a29.png">
<img width="512" alt="screenshot 2017-04-15 13 04 08" src="https://cloud.githubusercontent.com/assets/15153547/25060936/574b9cf2-21dc-11e7-8cfd-00e84565af08.png">
AND FROM WINDOWS 10:
<img width="767" alt="screenshot 2017-04-15 13 04 40" src="https://cloud.githubusercontent.com/assets/15153547/25060937/6712f43c-21dc-11e7-9f26-0a299db22c48.png">

**Comment by finalion** [comment]
@lobstergy Thanks for your feedback. I have fixed this key error and you could retry it.

**Comment by lobstergy** [comment]
@finalion Wow, it's very something for your response so quickly. I'll try it right away. Delete it and redownload, right? I'll feedback after that. Thanks, really!

**Comment by finalion** [comment]
Exactly, but you also only can download and replace context.py.

**Comment by lobstergy** [comment]
@finalion Hi, I'd tried that, now it can run normally, very nice! 
But, the dictionary I choose which is "oxford dictionary of English 3e", it seems that the add-on cannot display the media material right, led to many blank or wired items left in the definition section. Shown like blow, any idea?
1. Field I'd chosen
<img width="533" alt="screenshot 2017-04-15 17 56 11" src="https://cloud.githubusercontent.com/assets/15153547/25062770/d93ebf22-2205-11e7-8c36-80ffaabe9a26.png">
2.The anki preview after querying on mac
<img width="1603" alt="screenshot 2017-04-15 18 07 20" src="https://cloud.githubusercontent.com/assets/15153547/25062828/4f692402-2207-11e7-9e10-408f0c3f19bf.png">
3.The original dictionary display on pc
<img width="1287" alt="screenshot 2017-04-15 17 15 36" src="https://cloud.githubusercontent.com/assets/15153547/25062834/7b3f5d58-2207-11e7-8072-8b782e1479f1.png">
4.The original dictionary display on android phone in mdict
<img width="1287" alt="screenshot_20170415-175002"
src="https://cloud.githubusercontent.com/assets/15153547/25062909/b4677b64-2208-11e7-8dc5-94597ba20eca.png">

**Comment by finalion** [comment]
The formats are usually different for different dictionaries. So I am not sure it works on the dictionaries I didn't test. 

I am outside now and may review the codes at later time. Be patient. Thanks.

**Comment by lobstergy** [comment]
Yeah, I've noticed that the dictionary I use didn't have dictionary fields to choose from, unlike the online dictionaries you provided. Maybe that maters.
Very gratefully for your response and help, looking forward for the further progress whenever at your conveniences. Thanks again.

**Comment by finalion** [comment]
@lobstergy This dictionary can work on my anki. Can you paste your generated html codes here? 
![1](https://cloud.githubusercontent.com/assets/1539035/25065753/b14f7ade-221d-11e7-8cf2-05563a929e60.png)

**Comment by lobstergy** [comment]
@finalion That exactly what it should be, wish I could figure out makes it works like yours. I'm not sure how to generate HTML codes, is it the card template or the definition field in HTML form? I paste both separately blew:
**1. In add card process, the definition field in "edit HTML":**

<img width="1359" alt="screenshot 2017-04-16 11 16 19" src="https://cloud.githubusercontent.com/assets/15153547/25068436/2869fe78-2296-11e7-8696-2c05514f0820.png">

**2.In Browse->decks->Cards..., templates:**

<img width="1359" alt="screenshot 2017-04-16 11 21 40" src="https://cloud.githubusercontent.com/assets/15153547/25068458/f94ad22e-2296-11e7-9360-ee25cb353636.png">


[definition field & card template in html form.zip](https://github.com/finalion/WordQuery/files/924075/definition.field.card.template.in.html.form.zip)

**Comment by finalion** [comment]
You can check if the images in html have generated in the media folder, such as "_mortar-weapon.png".

**Comment by lobstergy** [comment]
@finalion Finally figure it out, and works charmingly! I can assure that the add-on functional well. Just for a normal user without a lot of technic skills, the process of troubleshooting can be time-consuming and a little bit of frustrating, so I share mine for others references: 
1. Dictionaries themselves, by lack of support source files/ folders, ended up missing pictures; 
2. Mistaken chosen the wrong note types for existent cards which had been assigned to different note types. (cards built by "Anki sweep words collector helper"-anki划词助手, another great add-on for Anki), leads the query fields cannot match correspondingly. 
Thanks, truly, for all your quick responses, help and the great add-on.

<img width="648" alt="screenshot 2017-04-17 16 13 34" src="https://cloud.githubusercontent.com/assets/15153547/25083291/da1cf218-2388-11e7-83bf-6a4390aef152.png">
