### ISSUE TITLE
可以增加爱词霸字典支持吗？

### ISSUE THREAD

**Issue by ehudu** [finalion/WordQuery#33]
http://www.iciba.com/
发音比较正常。

**Comment by finalion** [comment]
@ehudu 加了，试一下。直接下载service文件夹中的iciba.py即可。

**Comment by ehudu** [comment]
@finalion 使用查询全部字段时发现释义字段内容查不到（只有例句没查询）。但是单独查询释义字段它又能找到内容。有时美式发音又找不到。比如试下limes与lime两个单词。

**Comment by finalion** [comment]
@ehudu 已更新。又添加了几个字段。

**Comment by ehudu** [comment]
@finalion   更新了odds.py和iciba.py查询单词line可以正常，但是查询复数limes美式发音还是查不到。原网站是有美式发音的。

**Comment by finalion** [comment]
@ehudu 我看了那个确实没有啊。只有音标，没有发音。你可以再试下其他单词

**Comment by ehudu** [comment]
@finalion 恩，确实发现了。可能是从源码中看不到有复数单词的发音，复数的单词发音从浏览器打开是有发音的，可能是从别的网站上合成的发音。不过影响不大。

**Comment by finalion** [comment]
@ehudu 看了下，缺失的字段是用tts发音代替的。你再试下

**Comment by ehudu** [comment]
@finalion 试了下，可以了。
