### ISSUE TITLE
查询失败会卡住

### ISSUE THREAD

**Issue by ehudu** [finalion/WordQuery#36]
某种原因导致查询失败，可能是访问太快对方的接口？然后就会一起卡在那里，并且关闭后再重新查询发现插件失效，要重新启动软件才可以。建议增加超时跳过处理。

**Comment by finalion** [comment]
@ehudu 关闭进度框再重新查询的问题解决了。 哪个字典查询失败？现在也有超时机制。

**Comment by ehudu** [comment]
@finalion 应该是百词斩查询图片时，还有图片最好是能保存在本地的形式，我发现手机没网络时图片不显示。

**Comment by finalion** [comment]
@ehudu Updated.
