### ISSUE TITLE
Local dictionary indexing takes a long time

### ISSUE THREAD

**Issue by GarrisonBaird** [finalion/WordQuery#42]
If there are bunches of local dictionaries configured, it will take a long time to index, and the plugin do the indexing everytime Anki is started, users have to wait a long time even they are not going to use it. 

So here few solutions:
- Add an option to let users choose when the dictionaries should be indexed
- Index dictionaries at the first querying, instead of during the plugin initialization
- Index the specific dictionary once it's needed

**Comment by finalion** [comment]
I thought about these solutions before, but there would produce some other problems either. The important one is that the dictionaries' name list and field list in the dropdown controls could not be updated if some dictionaries have been removed since the last time when anki was closed.

**Comment by GarrisonBaird** [comment]
Maybe we can only grab the metadata during the plugin initialization. 
[_StarDictIfo](https://github.com/finalion/WordQuery/blob/master/wquery/libs/pystardict.py#L439)

**Comment by GarrisonBaird** [comment]
And also we can do the indexing once the plugin is invoked by the user

**Comment by finalion** [comment]
@GarrisonBaird Hi, I opened a dev branch and improved a lot in dictionary indexing.  You can help to test it.

**Comment by finalion** [comment]
I have merged to the master branch.

**Comment by GarrisonBaird** [comment]
Sorry to be absent, I'll test it these days, but I belive it will work fine ;)
