### ISSUE TITLE
new Version no work

### ISSUE THREAD

**Issue by HosseinAlipour** [finalion/WordQuery#47]
I just updated by downloading the zip from GitHub and copying the content to add-on folder and it seems it doesn't work at all, as soon as I click at 'query' it pop ups and go away without any effect like nothing happen in backstage.
I removed the add-on, this time I installed it from Anki add-on page and the same result again!
could you please help?

**Comment by finalion** [comment]
@HosseinAlipour I have a little update and please try to update the "query.py"

**Comment by finalion** [comment]
If it works, please let me know, thanks.

**Comment by HosseinAlipour** [comment]
got fixed! Thank you!
