### ISSUE TITLE
German dictionary ?

### ISSUE THREAD

**Issue by Anas11122** [finalion/WordQuery#50]
Can I add german dicitionary for this add-on ? If yes, How can I do so please ?

**Comment by finalion** [comment]
Yes, of course. Do that following the guide, if you have some german dictionaries.

**Comment by Anas11122** [comment]
I don't actually. Where can I get german dictionaries that can be added to this useful tool ?

**Comment by finalion** [comment]
There are some available options here and you can try. https://drive.google.com/file/d/0B4ElNFvKVd6FQjhiWmdnUy02OVU/view?usp=sharing
