### ISSUE TITLE
是否可以人人词典的场景例句图片获取?

### ISSUE THREAD

**Issue by j84lee** [finalion/WordQuery#51]
### Whether it can be reproduced

您好,我只懂一点点html编写知识, 想问是否可以参照哪个例子,自己添加一下人人词典里面的场景. 但是好像人人词典好像没有jason格式? 如何知道人人词典的返回jason的位置? 或者我是否能直接通过页面element扒页面? 不好意思不是很懂python和爬虫技术. 不知道是否可以予以简单的指导,比如我可以参照您那部分写一下, 或者有哪类文章我可以看学习一下. 
十分感谢

**Comment by finalion** [comment]
@j84lee 没有json格式可以从html获取的，用beautifulsoup或者正则都可以，你可以参考下service文件夹下面的youdao.py，bing.py等等。

**Comment by j84lee** [comment]
多谢啦

**Comment by GarrisonBaird** [comment]
Note that anki built-in beautifulsoup is an old version, **[bs3](https://www.crummy.com/software/BeautifulSoup/bs3/)**, see [frdic.py](/finalion/WordQuery/blob/master/wquery/service/frdic.py)

**Comment by j84lee** [comment]
@GarrisonBaird thanks👍
