### ISSUE TITLE
查询字段无单词

### ISSUE THREAD

**Issue by pe200012** [finalion/WordQuery#61]
### Wrong behavior 
我刚安装这个插件来试一试，结果毫无效果
输入单词并不能查阅
![default](https://user-images.githubusercontent.com/13463539/30520885-cbb893ca-9be8-11e7-8100-b7b14bdbf627.png)

### When it happened
当我制作卡片的时候
### Whether it can be reproduced
是的

###  The Dictionary
朗文词典(mdict), 字典字段只有default

请问该如何使用它？

**Comment by finalion** [comment]
插件设置的单词字段为哪个？

**Comment by pe200012** [comment]
朗文和牛津都只有default, 只有在线的有道等可以用。

**Comment by finalion** [comment]
你要查询的字段设置为第一个，即在选项里，选中第一个单选框。
