### ISSUE TITLE
能添加查询韩语的 naver 词典吗？

### ISSUE THREAD

**Issue by lyfd123** [finalion/WordQuery#62]
学习韩语时经常要在 naver 词典中查询单词再复制释义到 anki 中，很繁琐。作者能把 naver 的在线查词添加到词典列表里吗，或者告诉下怎么修改插件？

以 “중국”（中国）单词为例，naver 词典的查询链接是 http://cndic.naver.com/search/all?q=중국

**Comment by finalion** [comment]
Please see this section: https://github.com/finalion/WordQuery#service-customization
