### ISSUE TITLE
After adding new imports in .py files service disappear

### ISSUE THREAD

**Issue by superpawko** [finalion/WordQuery#64]
### Wrong behavior 
Service disappear when i add custom import example: "from bs4 import BeautifulSoup". I tried importing lxml and it also disappear.
### When it happened
After changing .py files in services. 
### Whether it can be **reproduced**

Here is my .py file for LDOCE6

#-*- coding:utf-8 -*-
import re
from bs4 import BeautifulSoup
from aqt.utils import showInfo, showText

from .base import export, with_styles, register, MdxService

path = u'C:\\Dictionaries\\LDOCE6\\LDOCE6.mdx'

@register(u'LDOCE6p')
class Ldoce6(MdxService):

    def __init__(self, dict_path):
        super(Ldoce6, self).__init__(path)

    @property
    def unique(self):
        return self.__class__.__name__

    @property
    def title(self):
        return self.__register_label__

    @export(u'Dict_pron', 1)
    def fld_phonetic(self):
        html = self.get_html()
        m = re.search(r'<span class="pron">(.*?)</span>', html)
        if m:
            return m.groups()[0]
        return ''

    @export(u'Dict_def', 2)
    def fld_explains(self):
        html = self.get_html()
        m = re.search(r'<span class="def">(.*?)</span>', html)
        if m:
            return m.groups()[0]
        return ''

    @export(u'Dict_entryhead', 3)
    def fld_explains2(self):
        html = self.get_html()
        m = re.search(r'<span class="entryhead">(.*?)<span class="buttons">', html)
        if m:
            return " ".join(m.groups())
        return ''

    @export(u'Dict_sense', 4)
    def fld_explains3(self):
        html = self.get_html()
        m = re.search(r'<span class="sense newline">(.*?)</span>', html)
        if m:
            return m.groups()[0]
        return ''

    @export(u'Dict_exmpl', 5)
    def fld_example(self):
        html = self.get_html()
        m = re.findall(r'<span class="example">(.*?)</span>', html)
        nonBreakSpace = u'\xa0'
        if m:
            str = "<br>".join(m)
            str = re.sub('<a.*?</a>','',str)
            str = re.sub('</span>','',str)
            str = str.replace(nonBreakSpace,'<span class="new33">» </span>')
            return str
        return ''

    @export(u'Dict_exmpl2', 6)
    def fld_example(self):
        html = self.get_html()
        m = tree.xpath('//span[@class="example"]/text()')
        nonBreakSpace = u'\xa0'
        if m:
            str = "<br>".join(m)
            str = re.sub('<a.*?</a>','',str)
            str = re.sub('</span>','',str)
            str = str.replace(nonBreakSpace,'<span class="new33">» </span>')
            return str
        return ''
		
    @export(u'Dict_exmpl3', 7)
    def fld_example(self):
        html = self.get_html()
        soup = BeautifulSoup(html)
        m = html.find_all('span',attrs={'class':'example'})
        nonBreakSpace = u'\xa0'
        if m:
            str = "<br>".join(m)
            str = re.sub('<a.*?</a>','',str)
            str = re.sub('</span>','',str)
            str = str.replace(nonBreakSpace,'<span class="new33">» </span>')
            return str
        return ''

**Comment by finalion** [comment]
Anki use an old version of Beautifulsoup, so don't use bs4, try "from Beautifulsoup import Beautifulsoup"
