### ISSUE TITLE
请问能不能导入词典default时，卡片back（就是词意面）不再显示一遍词头？

### ISSUE THREAD

**Issue by 36jerry** [finalion/WordQuery#70]
请问能不能导入词典default时，card back（就是词意面）不再显示一遍词头？卡片back显示词头的话，就不能再做成reversed card使用了

**Comment by songyunlai** [comment]
将{{FrontSide}}删掉就行了

**Comment by 36jerry** [comment]
https://raw.githubusercontent.com/finalion/WordQuery/master/screenshots/editor.png 
{{FrontSide}}去掉后，基本释义中仍有单词double显示啊

**Comment by GarrisonBaird** [comment]
Reversed card can be edited separately
