### ISSUE TITLE
如果找不到单词可否跳过呢

### ISSUE THREAD

**Issue by EnzioChen** [finalion/WordQuery#74]
我之前已经做了一个牌组,不过我现在想用WordQuery把卡片的内容换一下.

不过现在的情况就是,在使用WordQuery的时候,如果在MDX搜索到了单词,的确会把内容换成新的,不过如果查不到的话,就会把我原有的内容给清空了.这很让我郁闷.

不知道能否加个选项,搜索不到的时候不会用空内容覆盖,而是跳过呢.

**Comment by finalion** [comment]
加了一个界面，可设置参数“强制更新” 非选中即可。

**Comment by finalion** [comment]
@EnzioChen 问题是否解决？解决的话，请关闭这个issue
