### ISSUE TITLE
vocabulary.com的接口似乎失效了

### ISSUE THREAD

**Issue by dog-2** [finalion/WordQuery#8]
系统win7，错误如下图：

![image](https://cloud.githubusercontent.com/assets/5821479/21894824/8b1d8928-d91b-11e6-961c-1bb9677ba0b4.png)

MacOS上测试也无效，但是不会弹窗报错，但查询完毕后目标字段为空。
浏览器是可以正常访问vocabulary.com。

如上过程翻墙操作结果相同。

观察错误，似乎是vocabulary.com页面改变，导致正则失效的缘故。
前几天还特别好用的，不知道是我这边环境的问题，还是vocabulary.com更改导致的。

**Comment by finalion** [comment]
确实有问题，urllib2打开ssl出错

**Comment by dog-2** [comment]
暂时绕着圈解决了。。

不知道为什么urllib2直接请求网站的ssl连接会不成功，但是如果proxychains挂SS代理启动的ipython里测试，再用urllib2跑就能够返回。感觉可能是墙的锅。。

后来在本地做了个http的反向代理，然后改了service目录插件的请求地址到本地，才能够正常制卡。

anyway，感谢作者写出这么好的工具 : )
