### ISSUE TITLE
how does Word Query add-on work?

### ISSUE THREAD

**Issue by omega3** [finalion/WordQuery#90]
The description is nor clear.

"This addon is developed to emancipate you from the tedious work of looking up words in dictionary and pasting the explanations to anki whenever new language-learning cards are to be made."

Does it suppose to create new cards?

I'm asking because it doesn't work for me with starddict format dictionary. Can explain to me how to set it up correctly?

"The "Dict" comoboxes are used to specify the dictionaries. The "Dict fields" comoboxes are used to specify the available dictionary fields."

On the left column I chose dictionary but on the right I have only default.

I chose note type and added two fields to note type: one that I place a word that I want to find definition for and second field - where I want this definition to be displayed (the second field I made visible in template). When I press Ctrl+Q something is being processed but I don't get results. Any how-to would be welcomed.

**Comment by finalion** [comment]
yes, only "default" option. You can have some other options unless you or some others customize the dictionary.
It looks there was no something wrong with your steps. And check your dictionary, maybe?

**Comment by omega3** [comment]
Can you please explain in more detail this:

"and pasting the explanations to anki whenever new language-learning cards are to be made"

I don't understand it.
What it is actually suppose to do? What should be the correct effect and sign that it works properly? Creating new cards?

Is it possible to create such an add-on that would not paste but only display the content of dictionary based on a headword, for example that would read a headword from one Anki field and display definition from dictionary (like stardict dictionary file) to another field so that it would be visible in Anki display / learning mode without copy / paste anything to Anki  (so that Anki file don't get unnecessary bigger).

**Comment by GarrisonBaird** [comment]
It will query the word from the `field` that you specified (the radio button on the left), in the dictionary(dropdown list) that you specified, and write the query result back to another `field` that you specified (the field that you selected the dictionary) in the same `note`. You have to define these stuff for each type of note before it can actually work.
Yes, everything is possible. But an easier solution is that you set up a dictionary software like GoldenDict, which monitors the clipboard, select and copy the word that you want to search, then you will get a popup by the dictionary.

**Comment by shiningmatcha** [comment]
So I can use GoldenDict in combination with WordQuery?

**Comment by GarrisonBaird** [comment]
@shiningmatcha Use GoldenDict for instant explanations, use WordQuery for writing explanations into anki cards, depends on your need

**Comment by mdm508** [comment]
@GarrisonBaird  If you wouldn't mind elaborating on that last point. I am really confused on how to get WordQuery to use my GoldenDict Dictionaries. 

For example, I have Italian-English dictionary. I have pointed WordQuery to that folder but it doesnt give me this dictionary in the dropdown. Not sure if it matters but im on a mac.

**Comment by mdm508** [comment]
> Yes, everything is possible. But an easier solution is that you set up a dictionary software like GoldenDict, which monitors the clipboard, select and copy the word that you want to search, then you will get a popup by the dictionary.


Could you elaborate on this. I want to do this solution but its not clear to me how i can use golden dict with word query

**Comment by GarrisonBaird** [comment]
@mdm508 In this case, you don't need WordQuery at all. Set up GoldenDict, in `Edit` `Preferences` `Hotkeys` `Use the following hotkey to translate a word from clipboard` `Ctrl+C+C`. Then in Anki, select or double click the word you need to query, hold `CMD` and press `C` two times, you will get a popup by GoldenDict.
WordQuery and GoldenDict don't work together, but they can make use of the two dictionary formats in common
