### ISSUE TITLE
在 Mac 中没有 option 这个选项

### ISSUE THREAD

**Issue by LeonZ7991** [finalion/WordQuery#95]
你好，在 Mac 中我发现没有 option 这个选项设置字典，这是 bug 吗

**Comment by LeonZ7991** [comment]
我知道问题所在了，虽然没有这个选项，但是可以在工具中找到 wordquery 直接点击，然后进入 option 界面

**Comment by finalion** [comment]
@LeonZ7991 这就是正常的进入方式啊
